name: Dependabot for Clojure

on:
  #schedule:
    # Every Monday at 8AM UTC (9AM CEST)
    #- cron: '0 8 * * 1'
  # We can also trigger the workflow manually
  workflow_dispatch:

env:
  GITHUB_PAT: ${{ secrets.CLJ_DEPENDABOT_PAT }}
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_WORKSPACE: ${{ github.workspace }}

jobs:
  security-updates:
    name: 'Security updates'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependabot for Clojure security updates
        uses: luigigubello/clojure-dependabot@main
        with:
          main_branch: 'master'
          update_omitted: true
          include_subdirectories: false
          verbose: true
  #generic-updates:
  #  name: 'Important updates'
  #  runs-on: ubuntu-latest
  #  continue-on-error: true
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
      - name: Dependabot for Clojure generic updates
        uses: luigigubello/clojure-dependabot@main
        with:
          main_branch: 'master'
          security_updates_only: false
          update_omitted: true
          allow_dependency: 'org.clojure/clojure'
          include_subdirectories: false
          verbose: true
